### ISSUE TITLE
clear() throws java.lang.UnsupportedOperationException: remove

### ISSUE THREAD

**Issue by maxim5** [yahoo/Oak#173]
Create a map and call `.clear()`:
```
java.lang.UnsupportedOperationException: remove

	at java.base/java.util.Iterator.remove(Iterator.java:102)
	at java.base/java.util.AbstractCollection.clear(AbstractCollection.java:431)
	at java.base/java.util.AbstractMap.clear(AbstractMap.java:297)
```

**Comment by sanastas** [comment]
Indeed those optional APIs are not yet implemented. They are on the TODO list. Meanwhile instead of `Iterator.remove()` it is possible to use an iterator and invoke `remove()` on relevant key-value mapping. For `clear()` there is no good alternative. Using `close()` and building again will release the entire off-heap memory and allocate again.
