### ISSUE TITLE
infinite loop in ThreadIndexCalculator

### ISSUE THREAD

**Issue by liuxinpeister** [yahoo/Oak#207]
Hi! i got infinite loop in ThreadIndexCalculator when i remove value from OrderedMap

`"Thread-27" #690 prio=10 os_prio=0 tid=0x00007f45fc001800 nid=0xc029 runnable [0x00007f3e9dadc000]
   java.lang.Thread.State: RUNNABLE
        at com.yahoo.oak.ThreadIndexCalculator.getExistingIndex(ThreadIndexCalculator.java:36)
        at com.yahoo.oak.ThreadIndexCalculator.getIndex(ThreadIndexCalculator.java:44)
        at com.yahoo.oak.SyncRecycleMemoryManager$SliceSyncRecycle.release(SyncRecycleMemoryManager.java:225)
        at com.yahoo.oak.EntryOrderedSet.deleteValueFinish(EntryOrderedSet.java:222)
        at com.yahoo.oak.OrderedChunk.finalizeDeletion(OrderedChunk.java:355)
        at com.yahoo.oak.InternalOakBasics.finalizeDeletion(InternalOakBasics.java:310)
        at com.yahoo.oak.InternalOakBasics.remove(InternalOakBasics.java:240)
        at com.yahoo.oak.OakMap.remove(OakMap.java:146)
        at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - locked <0x00007f477589db18> (a com.hbird.moneytree.service.data.center.server.preload.HQCachePreloader)
        at com.hbird.moneytree.service.data.center.server.job.TimeWindowRefreshJob.executeHQCacheSyncToDB(TimeWindowRefreshJob.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)`

**Comment by liuxinpeister** [comment]
Maybe the reason is that this method is not called ： ThreadIndexCalculator.releaseIndex()

**Comment by sanastas** [comment]
Hi @liuxinpeister ,

With how many threads do you run? Is the failure re-creatable?

Generally, there is assert for infinite loop there, but most likely you are not running in debug mode.
